[[ops]]
name = "server"
lib_name = "read_write_server"

[[ops]]
name = "reader"
lib_name = "read_write_server"

[[ops]]
name = "writer"
lib_name = "read_write_server"

[[nodes]]
name = "node1"
hostname = "0.0.0.0"
port = 3000

[placement]
  [[placement.server]]
  nodename = "node1"
  actor_name = "server"
  reader_addr = "reader"
  writer_addr = "writer"

  [[placement.reader]]
  nodename = "node1"
  actor_name = "reader"
  server_addr = "server"

  [[placement.writer]]
  nodename = "node1"
  actor_name = "writer"
  server_addr = "server"
