[[ops]]
name = "dynamo_node"
lib_name = "dynamo_new"

[[ops]]
name = "dynamo_client"
lib_name = "dynamo_new"

[[nodes]]
name = "node1"
hostname = "0.0.0.0"
port = 3000

[placement]
  # spawn 5 dynamo nodes
  [[placement.dynamo_node]]
  nodename = "node1"
  actor_name = "nodeA"
  node_id = "nodeA"
  nodes = ["nodeA","nodeB","nodeC","nodeD","nodeE"]
  N = 3
  W = 2
  R = 2
  T = 10

  [[placement.dynamo_node]]
  nodename = "node1"
  actor_name = "nodeB"
  node_id = "nodeB"
  nodes = ["nodeA","nodeB","nodeC","nodeD","nodeE"]
  N = 3
  W = 2
  R = 2
  T = 10

  [[placement.dynamo_node]]
  nodename = "node1"
  actor_name = "nodeC"
  node_id = "nodeC"
  nodes = ["nodeA","nodeB","nodeC","nodeD","nodeE"]
  N = 3
  W = 2
  R = 2
  T = 10

  [[placement.dynamo_node]]
  nodename = "node1"
  actor_name = "nodeD"
  node_id = "nodeD"
  nodes = ["nodeA","nodeB","nodeC","nodeD","nodeE"]
  N = 3
  W = 2
  R = 2
  T = 10

  [[placement.dynamo_node]]
  nodename = "node1"
  actor_name = "nodeE"
  node_id = "nodeE"
  nodes = ["nodeA","nodeB","nodeC","nodeD","nodeE"]
  N = 3
  W = 2
  R = 2
  T = 10

  # client
  [[placement.dynamo_client]]
  nodename = "node1"
  actor_name = "client1"
  client_id = "client1"
  nodes = ["nodeA","nodeB","nodeC","nodeD","nodeE"]
