name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain components
      run: rustup component add clippy rustfmt

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run Ping Pong
      run: |
          cd examples/ping_pong
          make node &
          sleep 1
          
          timeout 6s make job || echo "make job terminated after timeout"
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 124 ]; then
              echo "make job failed"
              exit $status
          fi

    - name: Run Read-Write Server
      run: |
          cd examples/read_write_server
          make node &
          sleep 1
          
          timeout 6s make job || echo "make job terminated after timeout"
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 124 ]; then
              echo "make job failed"
              exit $status
          fi

    - name: Run Paxos
      run: |
          cd examples/paxos
          make node &
          sleep 1
          
          timeout 6s make job || echo "make job terminated after timeout"
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 124 ]; then
              echo "make job failed"
              exit $status
          fi

    - name: Run AB
      run: |
          cd examples/ab
          make node &
          sleep 1
          
          timeout 6s make job || echo "make job terminated after timeout"
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 124 ]; then
              echo "make job failed"
              exit $status
          fi
